import RPi.GPIO as GPIO
import time
n=10
while n>0:
    GPIO.setmode(GPIO.BOARD)
    GPIO.setup(7,GPIO.OUT)
    GPIO.setup(16,GPIO.OUT)
    GPIO.setup(40,GPIO.OUT)
    GPIO.setup(11,GPIO.OUT)
    GPIO.setup(13,GPIO.IN)
    GPIO.setup(36,GPIO.OUT)
    GPIO.setup(3,GPIO.OUT)
    GPIO.setup(5,GPIO.IN)
    GPIO.setup(22,GPIO.OUT)
    GPIO.setup(37,GPIO.OUT)
    GPIO.setup(12,GPIO.OUT)
    GPIO.setup(24,GPIO.OUT)
    GPIO.setup(32,GPIO.OUT)
    GPIO.setup(8,GPIO.OUT)
    GPIO.setup(26,GPIO.OUT)
    GPIO.setup(10,GPIO.OUT)
    GPIO.setup(35,GPIO.OUT)
    GPIO.setup(31,GPIO.OUT)
    GPIO.setup(38,GPIO.OUT)
    GPIO.setup(19,GPIO.OUT)
    GPIO.setup(33,GPIO.IN)
    GPIO.setup(29,GPIO.IN)
    GPIO.setup(23,GPIO.IN)
    GPIO.setup(21,GPIO.IN)
    n-=1
    print(n)
    for i in range(0,3):
        GPIO.output(7,True)
        time.sleep(0.05)
        GPIO.output(7,False)
        GPIO.output(16,True)
        time.sleep(0.05)
        GPIO.output(16,False)
        time.sleep(0.05)
        GPIO.output(40,True)
        time.sleep(0.05)
        GPIO.output(40,False)
        time.sleep(0.05)
        GPIO.output(11,False)
        GPIO.output(3,False)
        GPIO.output(35,False)
        GPIO.output(31,False)
        GPIO.output(38,False)
        GPIO.output(19,False)

        GPIO.output(36,True)
        time.sleep(0.05)
        GPIO.output(36,False)
        GPIO.output(22,True)
        time.sleep(0.05)
        GPIO.output(22,False)
        GPIO.output(37,True)
        time.sleep(0.05)
        GPIO.output(37,False)

        GPIO.output(12,True)
        time.sleep(0.05)
        GPIO.output(12,False)
        GPIO.output(24,True)
        time.sleep(0.05)
        GPIO.output(24,False)
        GPIO.output(32,True)
        time.sleep(0.05)
        GPIO.output(32,False)

        GPIO.output(8,True)
        time.sleep(0.05)
        GPIO.output(8,False)
        GPIO.output(26,True)
        time.sleep(0.05)
        GPIO.output(26,False)
        GPIO.output(10,True)
        time.sleep(0.05)
        GPIO.output(10,False)



    GPIO.cleanup()
